version: '3.9'

services:
  support-system:
    image: your-dockerhub-username/support-system:latest
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=console
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Talapass123!
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Talapass123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
